import { CreatePermissionDto } from '../../modules/role/dto/create-permission.dto';

export const permissionsData: CreatePermissionDto[] = [
  {
    name: 'user:list',
    key: 'user:list',
    description: 'List all users Pagination',
    groupName: 'User',
    groupKey: 'user',
    active: true,
  },
  {
    name: 'user:dropdown',
    key: 'user:dropdown',
    description: 'List dropdown users',
    groupName: 'User',
    groupKey: 'user',
    active: true,
  },
  {
    name: 'user:create',
    key: 'user:create',
    description: 'Create user',
    groupName: 'User',
    groupKey: 'user',
    active: true,
  },
  {
    name: 'user:setRoles',
    key: 'user:setRoles',
    description: 'Set roles for user',
    groupName: 'User',
    groupKey: 'user',
    active: true,
  },
  {
    name: 'user:view',
    key: 'user:view',
    description: 'View user',
    groupName: 'User',
    groupKey: 'user',
    active: true,
  },
  {
    name: 'user:edit',
    key: 'user:edit',
    description: 'Edit user',
    groupName: 'User',
    groupKey: 'user',
    active: true,
  },
  {
    name: 'user:delete',
    key: 'user:delete',
    description: 'Delete user',
    groupName: 'User',
    groupKey: 'user',
    active: true,
  },
  {
    name: 'role:list',
    key: 'role:list',
    description: 'List all roles Pagination',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'role:dropdown',
    key: 'role:dropdown',
    description: 'List dropdown roles',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'role:create',
    key: 'role:create',
    description: 'Create role',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'role:view',
    key: 'role:view',
    description: 'View role',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'role:edit',
    key: 'role:edit',
    description: 'Edit role',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'role:delete',
    key: 'role:delete',
    description: 'Delete role',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'role:permission:create',
    key: 'role:permission:create',
    description: 'Set permissions for role',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'role:permission:view',
    key: 'role:permission:view',
    description: 'View permissions for role',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
  {
    name: 'project:list',
    key: 'project:list',
    description: 'List all projects Pagination',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:dropdown',
    key: 'project:dropdown',
    description: 'List dropdown projects',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:create',
    key: 'project:create',
    description: 'Create project',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:view',
    key: 'project:view',
    description: 'View project',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:edit',
    key: 'project:edit',
    description: 'Edit project',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:delete',
    key: 'project:delete',
    description: 'Delete project',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:users:create',
    key: 'project:users:create',
    description: 'Create users for project',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:users:delete',
    key: 'project:users:delete',
    description: 'delete users for project',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'project:users:list',
    key: 'project:users:list',
    description: 'List users for project',
    groupName: 'Project',
    groupKey: 'project',
    active: true,
  },
  {
    name: 'issueType:create',
    key: 'issueType:create',
    description: 'Create issue type',
    groupName: 'IssueType',
    groupKey: 'issueType',
    active: true,
  },
  {
    name: 'issueType:list',
    key: 'issueType:list',
    description: 'List all issue types',
    groupName: 'IssueType',
    groupKey: 'issueType',
    active: true,
  },
  {
    name: 'issueType:view',
    key: 'issueType:view',
    description: 'View issue type',
    groupName: 'IssueType',
    groupKey: 'issueType',
    active: true,
  },
  {
    name: 'issueType:edit',
    key: 'issueType:edit',
    description: 'Edit issue type',
    groupName: 'IssueType',
    groupKey: 'issueType',
    active: true,
  },
  {
    name: 'issueType:delete',
    key: 'issueType:delete',
    description: 'Delete issue type',
    groupName: 'IssueType',
    groupKey: 'issueType',
    active: true,
  },
  {
    name: 'task:create',
    key: 'task:create',
    description: 'Create task',
    groupName: 'Task',
    groupKey: 'task',
    active: true,
  },
  {
    name: 'task:update',
    key: 'task:update',
    description: 'Update task',
    groupName: 'Task',
    groupKey: 'task',
    active: true,
  },
  {
    name: 'task:view',
    key: 'task:view',
    description: 'View task',
    groupName: 'Task',
    groupKey: 'task',
    active: true,
  },
  {
    name: 'task:list',
    key: 'task:list',
    description: 'list task',
    groupName: 'Task',
    groupKey: 'task',
    active: true,
  },
  {
    name: 'task:delete',
    key: 'task:delete',
    description: 'Delete task',
    groupName: 'Task',
    groupKey: 'task',
    active: true,
  },
  {
    name: 'board:create',
    key: 'board:create',
    description: 'Create board',
    groupName: 'Board',
    groupKey: 'board',
    active: true,
  },
  {
    name: 'board:list',
    key: 'board:list',
    description: 'List all boards',
    groupName: 'Board',
    groupKey: 'board',
    active: true,
  },
  {
    name: 'board:view',
    key: 'board:view',
    description: 'View board',
    groupName: 'Board',
    groupKey: 'board',
    active: true,
  },
  {
    name: 'board:edit',
    key: 'board:edit',
    description: 'Edit board',
    groupName: 'Board',
    groupKey: 'board',
    active: true,
  },
  {
    name: 'board:delete',
    key: 'board:delete',
    description: 'Delete board',
    groupName: 'Board',
    groupKey: 'board',
    active: true,
  },
  {
    name: 'epic:create',
    key: 'epic:create',
    description: 'Create epic',
    groupName: 'Epic',
    groupKey: 'epic',
    active: true,
  },
  {
    name: 'epic:view',
    key: 'epic:view',
    description: 'View epic',
    groupName: 'Epic',
    groupKey: 'epic',
    active: true,
  },
  {
    name: 'epic:edit',
    key: 'epic:edit',
    description: 'Edit epic',
    groupName: 'Epic',
    groupKey: 'epic',
    active: true,
  },
  {
    name: 'epic:list',
    key: 'epic:list',
    description: 'List all epics',
    groupName: 'Epic',
    groupKey: 'epic',
    active: true,
  },
  {
    name: 'epic:delete',
    key: 'epic:delete',
    description: 'Delete epic',
    groupName: 'Epic',
    groupKey: 'epic',
    active: true,
  },
  {
    name: 'permission:list',
    key: 'permission:list',
    description: 'Permission list',
    groupName: 'Role',
    groupKey: 'role',
    active: true,
  },
];
